apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: the-twit-hazelcast
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: the-twit-hazelcast
    spec:
      containers:
      - name: twit-worker
        image: gcr.io/the-twit-hazelcast/twit-worker
        ports:
        - containerPort: 5701
          name: hazel-port-1
        - containerPort: 5702
          name: hazel-port-2
        - containerPort: 5703
          name: hazel-port-3
        - containerPort: 5704
          name: hazel-port-4
        - containerPort: 5705
          name: hazel-port-5
