version: "3.3"
services:
  jenkins-master:
    build: .
    image: jenkins-master:v1
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - mvn_repo:/root/.m2
volumes:
  jenkins_home:
  mvn_repo: