apiVersion: v1
kind: Service
metadata:
  name: master-service
  labels:
    app: master
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4567
  selector:
    app: master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: master-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
      - name: master
        image: eu.gcr.io/apt-sentinel-180609/ta-master:v1
        imagePullPolicy: Always