apiVersion: v1
kind: Service
metadata:
  name: web-app-service
  labels:
    app: web-app
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4567
  selector:
    app: web-app
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web-app-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: eu.gcr.io/apt-sentinel-180609/ta-web-app:%VERSION%
        imagePullPolicy: Always
---
